version: 2.1
jobs:
  test:
    working_directory: ~/spark
    docker:
      - image: renegus/spark
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependency-cache-
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Setup Xvfb screen
          command: Xvfb :1 -screen 0 1024x768x16 &
          background: true
      - run:
          name: test
          command: npm run test
          environment:
            PXSCENE_PATH: '/usr/src/app/pxCore/examples/pxScene2d/src/spark.sh'
workflows:
  version: 2
  test:
    jobs:
      - test