version: 2.1
jobs:
  test:
    working_directory: ~/spark
    docker:
      - image: renegus/spark
        environment:
          DISPLAY: :0
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependency-cache-
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build project
          command: npm run build
      - run:
          name: test
          command: npm run test
          environment:
            PXSCENE_PATH: "xvfb-run --auto-servernum --server-args='-screen 0, 1024x768x16' /usr/src/app/pxCore/examples/pxScene2d/src/spark.sh"
      - store_artifacts:
          path: ~/spark/results
workflows:
  version: 2
  test:
    jobs:
      - test